spring:
  ## DataSource (MySQL) ##
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/toleave?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## GCP (???? ? ?? ??) ##
  cloud:
    gcp:
      project-id: toleave
      credentials:
        location: file:/Users/jjuchan/My/projects/Toleave/BE/backend/src/main/resources/toleave-b9a7b3a17267.json
