spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/toleave?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 19990524
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    gcp:
      project-id: toleave
      credentials:
        location: file:/Users/yeboong99/Desktop/toleave_back/backend/src/main/resources/toleave-b9a7b3a17267.json
