name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  # Job1: 빌드 검증 - 빌드 실패 시 이후 Job 전체 중단
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          # 아래 두 폴더를 압축하고
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

          # 압축된 두 파일을 깃허브 캐시 서버에 이 이름으로 저장 (아래 두 경로에서 변경이 발생하면 해시값이 바뀌어서 의존성이 업데이트되었는지 여부를 판단할 수 있음)
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*', 'backend/**/gradle-wrapper.properties') }}

          # key로 정확히 일치하는 캐시가 없다면 -> key의 뒷부분 두 경로를 해시한 값 앞에까지만이라도 같은 부분이 없는지 부분 일치로 대체탐색하는 fallback용 목록.
          # 여기에서까지 찾지 못하면 캐시가 없다고 판단하고(즉, 빌드 관련 파일 자체가 없다고 판단) 처음부터 다운로드
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build JAR
        run: ./gradlew bootJar --no-daemon -x test
        working-directory: backend

  # Job2: Semver 자동 태그 생성 + GitHub Release
  # - 커밋 메시지 프리픽스 (feat:, fix: 등)을 보고 Minor / Patch 판단, Semver 규칙 적용
  tag:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2 # semver 태그 자동화 오픈소스 액션
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch # 프리픽스 판단 불가 시 patch로 올림
          release_branches: main # 메인 브랜치에서만 릴리즈 태그 생성
          create_annotated_tag: true # annotated는 태그 생성자, 날짜, 메시지 등 메타데이터 포함

      - name: Create GitHub Release
        uses: actions/github-script@v7
        env:
          TAG_NAME: ${{ steps.tag_version.outputs.new_tag }} # 위 step의 output 태그이름(ex-'v0.0.1)과 태그 사이의 커밋 목록 텍스트를 환경변수로 주입
          CHANGELOG: ${{ steps.tag_version.outputs.changelog }}
        with:
          # 조직명, 레포명, 릴리즈태그, 커밋 목록 텍스트, GitHub 자동 릴리즈노트 Body 뒤에 추가
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.TAG_NAME,
              name: `Release ${process.env.TAG_NAME}`,
              body: process.env.CHANGELOG,
              generate_release_notes: true
            });
